# Site settings
title: Home Smart Home
description: L'électronique pour la domotique
cover: assets/images/arch-bridge.jpg
#logo: assets/images/dawn-desktop.jpg
favicon: assets/images/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
url: "https://dufoura.github.io/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  per_page: 5

# Social
#facebook: facebook
#twitter: twitter
github:  dufoura
email : arnaud31.dufour@gmail.com
linkedin : arnaud-dufour-56359663

#Additional Pages
about: about
contact: mailto:arnaud31.dufour@gmail.com
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: "G-PQ4M4YC4HZ"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: dufoura #github username
repo: dufoura.github.io #github repository
branch: master #branch
# relative_source: ../hanuman/ #source directory
# destination: ../hanuman-pages/ #destination directory
# production_url:  https://samanyougarg.com/
# source_url:  https://github.com/samanyougarg/hanuman #source repository url

# exclude:
  # - README.md
  # - Rakefile
  # - Gemfile
  # - Gemfile.lock
  # - changelog.md
  # - "*.Rmd"
  # - vendor
  # - .travis.yml